name: panscape
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - pip

  # Core Python dependencies
  - pydantic>=2.8,<3
  - pyyaml>=6,<7
  - rich>=13.7,<14
  - typer>=0.12,<1
  - pyrodigal>=3.5,<4

  # Dev/test tooling
  - pytest>=8.2
  - black>=24.4
  - ruff>=0.5
  - mypy>=1.10

  # External bioinformatics tools used by PanScape build/map
  - mash
  - skani
  - mmseqs2
  - checkm2=1.1.0
  - samtools
  - minimap2
  - bwa

  - pip:
      - types-PyYAML>=6.0.12.20241230
      - git+https://github.com/anttonalberdi/panscape.git
